// examples/tsx/components/richtext/ListItem.tsx
import { FSXABaseRichTextElement, FSXARichText } from "fsxa-pattern-library";
import Component from "vue-class-component";

@Component({
  name: "ListItem",
})
class ListItem extends FSXABaseRichTextElement {
  render() {
    return (
      <li>
        <FSXARichText content={this.content} />
      </li>
    );
  }
}
export default ListItem;

// examples/sfc/components/richtext/ListItem.vue
<template
  ><li>
    <render-content /></li
></template>
<script lang="ts">
import { FSXABaseRichTextElement } from "fsxa-pattern-library";
import { Component } from "vue-property-decorator";

@Component({
  name: "ListItem",
})
class ListItem extends FSXABaseRichTextElement {}
export default ListItem;
</script>
