// examples/tsx/components/richtext/List.tsx
import { FSXABaseRichTextElement, FSXARichText } from "fsxa-pattern-library";
import Component from "vue-class-component";

@Component({
  name: "List",
})
class List extends FSXABaseRichTextElement {
  render() {
    return (
      <ul>
        <FSXARichText content={this.content} />
      </ul>
    );
  }
}
export default List;

// examples/sfc/components/richtext/List.vue
<template
  ><ul>
    <render-content /></ul
></template>
<script lang="ts">
import { FSXABaseRichTextElement } from "fsxa-pattern-library";
import { Component } from "vue-property-decorator";

@Component({
  name: "List",
})
class List extends FSXABaseRichTextElement {}
export default List;
</script>
