// examples/tsx/components/richtext/Paragraph.tsx
import { FSXABaseRichTextElement, FSXARichText } from "fsxa-pattern-library";
import Component from "vue-class-component";

@Component({
  name: "Paragraph",
})
class Paragraph extends FSXABaseRichTextElement {
  render() {
    return (
      <p>
        <FSXARichText content={this.content} />
      </p>
    );
  }
}
export default Paragraph;

// examples/sfc/components/richtext/Paragraph.vue
<template
  ><p><rich-text :content="content" /></p
></template>
<script lang="ts">
import { FSXABaseRichTextElement, FSXARichText } from "fsxa-pattern-library";
import { Component } from "vue-property-decorator";

@Component({
  name: "Paragraph",
  components: {
    "rich-text": FSXARichText,
  },
})
class Paragraph extends FSXABaseRichTextElement {}
export default Paragraph;
</script>
