// examples/sfc/components/richtext/Text.vue
<template
  ><strong v-if="data.format === 'bold'"><render-content /></strong>
  <span v-else><render-content /></span
></template>
<script lang="ts">
import { FSXABaseRichTextElement } from "fsxa-pattern-library";
import { Component } from "vue-property-decorator";

@Component({
  name: "TextComp",
})
class Text extends FSXABaseRichTextElement {}
export default Text;
</script>

// examples/tsx/components/richtext/Text.tsx
import { FSXABaseRichTextElement } from "fsxa-pattern-library";
import Component from "vue-class-component";

@Component({
  name: "TextComponent",
})
class Text extends FSXABaseRichTextElement {
  render() {
    if (this.data.format === "bold") return <strong>{this.content}</strong>;
    if (this.data.format === "italic") return <em>{this.content}</em>;
    return typeof this.content === "string" ? (
      <span domPropsInnerHTML={this.content} />
    ) : (
      <span>{this.content}</span>
    );
  }
}
export default Text;
