// examples/tsx/components/layouts/StandardLayout.tsx
import Component from "vue-class-component";
import { FSXABaseLayout } from "fsxa-pattern-library";

@Component({
  name: "StandardLayout",
})
class StandardLayout extends FSXABaseLayout {
  render() {
    return (
      <div>
        {this.renderContentByName("default")}
        {this.renderContentByName("content")}
      </div>
    );
  }
}
export default StandardLayout;

// examples/sfc/components/layouts/StandardLayout.vue
<template>
  <div>
    <slot name="content" />
  </div>
</template>

<script lang="ts">
import { FSXABaseLayout } from "fsxa-pattern-library";
import Component from "vue-class-component";

@Component({ name: "StandardLayout" })
class StandardLayout extends FSXABaseLayout {}
export default StandardLayout;
</script>
